"""Adaptive Engineering Memory ingestion and storage components."""

from .bridge import build_cross_links
from .db_loader import Neo4jMemoryStore
from .ingestion_code import ingest_code, parse_graphify_graph
from .hybrid_retrieval import (
    HybridRetrievalService,
    SemanticKnowledgeIndex,
    hybrid_retrieve_engineering_memory,
)
from .models import (
    AISession,
    AISessionRecord,
    CandidateRankingScore,
    CodeSymbol,
    Document,
    DocumentEntity,
    EngineeringDecision,
    EngineeringEvent,
    GraphEdge,
    HybridQueryResponse,
    HybridRetrievalResult,
    IntentAnalysisResult,
    Memory,
    MemoryCategory,
    MemoryProvenance,
    MemoryQueryResponse,
    MemoryScope,
    Module,
    OptimizationComparison,
    OptimizationMode,
    OptimizedItemRecord,
    OrchestratedContext,
    Project,
    QueryIntent,
    RankingWeights,
    RecordSessionResponse,
    RelationshipHop,
    RemovedItemRecord,
    Repository,
    ResultProvenance,
    RetrievalResult,
    Team,
    TeamMembership,
    TokenOptimizationResult,
    User,
    scoped_id,
    utc_now_iso,
)
from .session_memory import (
    AISessionKnowledgeSummarizer,
    AISessionMemoryService,
    get_ai_session_api,
    get_default_session_service,
    query_ai_sessions_api,
    record_ai_session_api,
)
from .team_memory import (
    SessionKnowledgeDistiller,
    TeamMemoryService,
)
from .team_memory_store import (
    TeamMemoryDocumentStore,
)
from .token_optimizer import (
    BaseLLMCompressor,
    CandidateProvenanceAnchor,
    ContextTier,
    GeminiLLMCompressor,
    MockLLMCompressor,
    OpenAILLMCompressor,
    ProvenanceGuardrail,
    RedundancyDetector,
    TokenEstimator,
    TokenOptimizationEngine,
    compare_optimization_modes,
    extract_provenance_anchor,
    get_llm_compressor,
    optimize_tokens,
    render_candidate_item,
)
from .ranking import (
    BaseContextRanker,
    ConfigurableContextRanker,
    DEFAULT_SOURCE_RELIABILITY_MAP,
    adapt_weights_for_intent,
    compute_confidence,
    compute_freshness,
    compute_graph_relevance,
    compute_lexical_relevance,
    compute_repository_match,
    compute_semantic_relevance,
    compute_source_reliability,
    compute_token_cost_efficiency,
)
from .orchestrator import (
    AdaptiveContextOrchestrator,
    AdaptiveContextPacker,
    BaseContextPacker,
    BaseIntentClassifier,
    DEFAULT_INTENT_STRATEGIES,
    IntentAwareContextRanker,
    RuleBasedIntentClassifier,
    TokenOptimizedContextPacker,
    deduplicate_results,
    orchestrate_context,
)
from .normalization import (
    EntityKind,
    NormalizedEntity,
    are_compatible,
    compare_entities,
    detect_kind,
    normalize_entity,
    to_canonical,
    tokenize_name,
)
from .retrieval import (
    MemoryRetrievalService,
    query_engineering_memory,
)
from .semantic_matcher import (
    BaseEmbeddingProvider,
    GeminiEmbeddingProvider,
    MockEmbeddingProvider,
    OpenAIEmbeddingProvider,
    SemanticCandidateRetriever,
    SemanticSymbolIndex,
    get_embedding_provider,
)

__all__ = [
    "AISession",
    "AISessionKnowledgeSummarizer",
    "AISessionMemoryService",
    "AISessionRecord",
    "AdaptiveContextOrchestrator",
    "AdaptiveContextPacker",
    "BaseContextPacker",
    "BaseContextRanker",
    "BaseEmbeddingProvider",
    "BaseIntentClassifier",
    "BaseLLMCompressor",
    "CandidateProvenanceAnchor",
    "CandidateRankingScore",
    "CodeSymbol",
    "ConfigurableContextRanker",
    "ContextTier",
    "DEFAULT_INTENT_STRATEGIES",
    "DEFAULT_SOURCE_RELIABILITY_MAP",
    "Document",
    "DocumentEntity",
    "EngineeringDecision",
    "EngineeringEvent",
    "EntityKind",
    "GeminiEmbeddingProvider",
    "GeminiLLMCompressor",
    "GraphEdge",
    "HybridQueryResponse",
    "HybridRetrievalResult",
    "HybridRetrievalService",
    "IntentAnalysisResult",
    "IntentAwareContextRanker",
    "Memory",
    "MemoryCategory",
    "MemoryProvenance",
    "MemoryQueryResponse",
    "MemoryRetrievalService",
    "MemoryScope",
    "MockEmbeddingProvider",
    "MockLLMCompressor",
    "Module",
    "Neo4jMemoryStore",
    "NormalizedEntity",
    "OpenAIEmbeddingProvider",
    "OpenAILLMCompressor",
    "OptimizationComparison",
    "OptimizationMode",
    "OptimizedItemRecord",
    "OrchestratedContext",
    "Project",
    "ProvenanceGuardrail",
    "QueryIntent",
    "RankingWeights",
    "RecordSessionResponse",
    "RedundancyDetector",
    "RelationshipHop",
    "RemovedItemRecord",
    "Repository",
    "ResultProvenance",
    "RetrievalResult",
    "RuleBasedIntentClassifier",
    "SemanticCandidateRetriever",
    "SemanticKnowledgeIndex",
    "SemanticSymbolIndex",
    "SessionKnowledgeDistiller",
    "Team",
    "TeamMembership",
    "TeamMemoryDocumentStore",
    "TeamMemoryService",
    "TokenEstimator",
    "TokenOptimizationEngine",
    "TokenOptimizationResult",
    "TokenOptimizedContextPacker",
    "User",
    "adapt_weights_for_intent",
    "are_compatible",
    "build_cross_links",
    "compare_entities",
    "compare_optimization_modes",
    "compute_confidence",
    "compute_freshness",
    "compute_graph_relevance",
    "compute_lexical_relevance",
    "compute_repository_match",
    "compute_semantic_relevance",
    "compute_source_reliability",
    "compute_token_cost_efficiency",
    "get_ai_session_api",
    "get_default_session_service",
    "query_ai_sessions_api",
    "record_ai_session_api",
    "utc_now_iso",
    "deduplicate_results",
    "detect_kind",
    "extract_provenance_anchor",
    "get_embedding_provider",
    "get_llm_compressor",
    "hybrid_retrieve_engineering_memory",
    "ingest_code",
    "ingest_documents",
    "ingest_repository",
    "normalize_entity",
    "optimize_tokens",
    "orchestrate_context",
    "parse_graphify_graph",
    "query_engineering_memory",
    "render_candidate_item",
    "scoped_id",
    "to_canonical",
    "tokenize_name",
]


def ingest_documents(*args, **kwargs):
    """Lazy wrapper to prevent runpy RuntimeWarnings during direct module execution."""
    from .ingestion_docs import ingest_documents as _ingest_documents

    return _ingest_documents(*args, **kwargs)


def ingest_repository(*args, **kwargs):
    """Lazy wrapper to prevent runpy RuntimeWarnings during direct module execution."""
    from .pipeline import ingest_repository as _ingest_repository

    return _ingest_repository(*args, **kwargs)